"""Distill a trace into a minimal reproducing eval case."""

from __future__ import annotations

from postmortem.ingest.base import Trace
from postmortem.case import EvalCase, Assertion


class Distiller:
    """Extract minimal reproducing input and assertions from a trace."""

    def distill(self, trace: Trace) -> EvalCase:
        """Convert a trace into an EvalCase with input and assertions."""
        input_messages = self._extract_input(trace)
        assertions = self._generate_assertions(trace)
        label = self._infer_label(trace)

        return EvalCase(
            id=f"case-{trace.id}",
            label=label,
            input={"messages": [m.to_dict() for m in input_messages]},
            assertions=assertions,
        )

    def _extract_input(self, trace: Trace) -> list:
        """Extract the minimal input messages needed to reproduce.

        Includes user messages and system messages, but not assistant/tool
        responses (those should be regenerated by the agent).
        """
        from postmortem.ingest.base import TraceMessage

        messages = []
        for msg in trace.messages:
            if msg.role in ("user", "system"):
                messages.append(msg)
            # Stop after finding the first user message + any preceding system
            if msg.role == "user":
                break
        return messages if messages else trace.messages[:1]

    def _generate_assertions(self, trace: Trace) -> list[Assertion]:
        """Generate assertions based on the failure pattern."""
        assertions: list[Assertion] = []

        # Pattern 1: Tool error in output
        for msg in trace.messages:
            if msg.role == "tool" and msg.content:
                content = msg.content
                if any(kw in content.lower() for kw in ["error", "exception", "failed", "denied"]):
                    assertions.append(Assertion(
                        type="not_contains",
                        expected=content[:200],
                        description=f"Should not produce error: {content[:80]}",
                    ))

        # Pattern 2: Infinite loop detection (repeated tool calls)
        tool_calls = []
        for msg in trace.messages:
            for tc in msg.tool_calls:
                tool_calls.append(tc.get("name", ""))

        if self._has_loop(tool_calls):
            # Find the repeating tool
            from collections import Counter
            most_common = Counter(tool_calls).most_common(1)
            if most_common:
                tool_name = most_common[0][0]
                assertions.append(Assertion(
                    type="not_repeated",
                    expected=tool_name,
                    description=f"Should not loop on {tool_name} tool",
                ))

        # Pattern 3: Tool was called (positive assertion)
        if trace.messages:
            first_tools = set()
            for msg in trace.messages:
                for tc in msg.tool_calls:
                    first_tools.add(tc.get("name", ""))
            for tool_name in first_tools:
                assertions.append(Assertion(
                    type="tool_called",
                    expected=tool_name,
                    description=f"Should call {tool_name} tool",
                ))

        # Pattern 4: Expected output patterns
        if trace.outcome == "error" and trace.metadata.error:
            assertions.append(Assertion(
                type="not_contains",
                expected=trace.metadata.error[:200],
                description=f"Should not produce error: {trace.metadata.error[:80]}",
            ))

        # Always add a success check if we have few assertions
        if len(assertions) < 2:
            assertions.append(Assertion(
                type="status_code",
                expected="success",
                description="Should complete successfully",
            ))

        return assertions

    def _infer_label(self, trace: Trace) -> str:
        """Infer a human-readable label for the failure pattern."""
        tool_names = []
        for msg in trace.messages:
            for tc in msg.tool_calls:
                tool_names.append(tc.get("name", ""))

        if self._has_loop(tool_names):
            from collections import Counter
            most = Counter(tool_names).most_common(1)
            tool = most[0][0] if most else "unknown"
            return f"tool-loop-on-{tool}"

        for msg in trace.messages:
            if msg.role == "tool" and msg.content:
                content = msg.content.lower()
                if "permission denied" in content:
                    return "permission-denied-error"
                if "timeout" in content:
                    return "timeout-error"
                if "not found" in content:
                    return "not-found-error"

        if trace.outcome == "error":
            return f"error-{trace.id[:12]}"

        return f"failure-{trace.id[:12]}"

    @staticmethod
    def _has_loop(names: list[str], threshold: int = 3) -> bool:
        if len(names) < threshold:
            return False
        count = 1
        for i in range(1, len(names)):
            if names[i] == names[i - 1]:
                count += 1
                if count >= threshold:
                    return True
            else:
                count = 1
        return False
